### ISSUE TITLE
PHP error: JobQueueDB.php: Call to a member function getNamespace() on null

### ISSUE THREAD

**Issue by ciencia** [WikiApiary/WikiApiary#247] opened 2021-03-25 22:42 UTC
When creating a new page, I get this error:

```
[a348c093bbcc3e9d051b71f5] /wiki/Mystery_Dungeon_Franchise_Wiki Error from line 727 of /srv/www/mediawiki/public_html/w/includes/jobqueue/JobQueueDB.php: Call to a member function getNamespace() on null

Backtrace:

#0 /srv/www/mediawiki/public_html/w/includes/jobqueue/JobQueueDB.php(218): JobQueueDB->insertFields(PFCreatePageJob)
#1 /srv/www/mediawiki/public_html/w/includes/jobqueue/JobQueueDB.php(193): JobQueueDB->doBatchPushInternal(Wikimedia\Rdbms\DBConnRef, array, integer, string)
#2 /srv/www/mediawiki/public_html/w/includes/deferred/AutoCommitUpdate.php(42): JobQueueDB->{closure}(Wikimedia\Rdbms\DBConnRef, string)
#3 /srv/www/mediawiki/public_html/w/includes/deferred/DeferredUpdates.php(257): AutoCommitUpdate->doUpdate()
#4 /srv/www/mediawiki/public_html/w/includes/deferred/DeferredUpdates.php(210): DeferredUpdates::runUpdate(AutoCommitUpdate, Wikimedia\Rdbms\LBFactorySimple, string, integer)
#5 /srv/www/mediawiki/public_html/w/includes/deferred/DeferredUpdates.php(127): DeferredUpdates::execute(array, string, integer)
#6 /srv/www/mediawiki/public_html/w/includes/MediaWiki.php(603): DeferredUpdates::doUpdates(string, integer)
#7 /srv/www/mediawiki/public_html/w/includes/MediaWiki.php(572): MediaWiki::preOutputCommit(RequestContext, Closure)
#8 /srv/www/mediawiki/public_html/w/includes/MediaWiki.php(878): MediaWiki->doPreOutputCommit(Closure)
#9 /srv/www/mediawiki/public_html/w/includes/MediaWiki.php(523): MediaWiki->main()
#10 /srv/www/mediawiki/public_html/w/index.php(43): MediaWiki->run()
#11 {main}
```

The error seems to prevent the page from appearing in Recent Changes, links aren't updated (wiki logo doesn't appear as linked from the page, despite being in use on that page), etc.

You can probably reproduce it by purging the page

**Comment by kghbln** [comment] 2021-03-26 07:30
@ciencia This is most probably Page Forms and probably fixed in some recent version. Or at least it directly started after I added the autocreation functionality for farms and extensions. We have a backlog of about 4 years here. I guess I will revert this change once the job queue is empty.

**Comment by ciencia** [comment] 2021-04-05 18:44
I don't know why, but the error seems to be only happening to me, since only the pages I create are not appearing in RecentChanges, while page creations from other users are appearing there just fine.

I'll have to put page creations on hold until this gets fixed. Otherwise, bots will never notice that those pages are created, and it will only add inconsistencies to the database

**Comment by kghbln** [comment] 2021-04-06 08:28
Happens to me, too though I am not creating that many new pages. I have seed you adding wikis recently. Anyhow, I just commented out the wikitext from Page Forms autocreating pages, which triggered this issue in the first place. Hopefully this helps the cause.

**Closed as completed** 2021-04-07 17:39 UTC
