### ISSUE TITLE
Make Template:Website default to Special:Statistics collection for early MW versions

### ISSUE THREAD

**Issue by plexish** [WikiApiary/WikiApiary#121] opened 2014-06-09 11:02 UTC
I just turned Special:Statistics on for a handful of early MW version wikis, and they're now collecting data. Glancing over the generator stats, it looks like there's a significant number of wikis like this.

If the MW version is below the version statistics API was added collect could default to Special not API, and the Special:Statistics URL autogenerated by regex splitting the last part of Main Page url off (seems to be virtually always separated by / or =) and replacing it with Special:Statistics, that would let Wikiapiary collect from a lot more wikis without any bot changes (like #54).

**Comment by jthingelstad** [comment] 2014-06-09 12:08
This should be handled with #20 or #54 while doing #49.

**Comment by jthingelstad** [comment] 2014-06-09 12:09
Closing as duplicate of #20.

**Closed as completed by jthingelstad** 2014-06-09 12:09 UTC
Labels: duplicate
