### ISSUE TITLE
The languages tag seems to have gone

### ISSUE THREAD

**Issue by kghbln** [WikiApiary/WikiApiary#188] opened 2014-08-05 15:08 UTC
I am not sure if this is related to an upgrade or so, but probably. I opened a [thread of mw.o](https://www.mediawiki.org/wiki/Thread:Extension_talk:Translate/Tag_languages/_broken). Strange anyways...

**Comment by jthingelstad** [comment] 2014-08-09 00:47
That is seriously messed up. `<languages/>` doesn't work. `<languages />` does. Fixed with [this diff](https://wikiapiary.com/w/index.php?title=Main_Page&diff=1137663&oldid=1125468). Eek.

**Closed as completed by jthingelstad** 2014-08-09 00:47 UTC
Labels: wiki, sysadmin

**Comment by kghbln** [comment] 2014-08-09 07:26
I am still a bit puzzled. As [this page](https://wikiapiary.com/wiki/WikiApiary:Monitored_by) proves it is also working with `<languages/>`. However as the main page was not working this one was not either. Are you sure that this is the only thing you did?

**Comment by jthingelstad** [comment] 2014-08-10 01:14
I’m puzzled as well. I had to do a bunch of garbage on with LocalSettings.php to setup a new wiki. The Translate extension was causing `update.php` to fail to run and leaving me in a really bad spot. I ended up moving Translate out of composer so I could disable it, and it all ended up being a giant _PITA_. Anyway, it seems fine now but this odd behavior on this tag makes so little sense.

**Comment by kghbln** [comment] 2014-08-10 09:11
Ouch :( I just make @nikerabbit aware of this. Perhaps at one stage or the other the transgressing code will be spotted. Howerver, it is cool that it is working now.

**Comment by Nikerabbit** [comment] 2014-08-10 12:21
You [already told](https://www.mediawiki.org/wiki/Thread:Extension_talk:Translate/Tag_languages/_broken) me about the tag issue.

@thingles I assume you are running MediaWiki master with Translate from MLEB. Unfortunately core has an incompatible change you need latest development version of Translate.

**Comment by kghbln** [comment] 2014-08-10 14:42
Yes, but you told me that you cannot reproduce. Since I thought that this may provide further information in this case I figured that it may be of advantage to keep you in the loop somehow. I have been proven wrong an I apologize for having bothered you.

**Comment by Nikerabbit** [comment] 2014-08-12 12:53
There is no reason to apologize. I still can't reproduce the issue and I still suspect it is interference from other code and possibly a race condition as it does not seem to happen always. Caching (many layers) adds to the confusion.
